print("""Project Euler 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.""")


Fibonacci_seq = [1,2]
total = 2
n = int(input("\nPlease provide the input \n"))
while Fibonacci_seq[-1] < n:
    next_i = Fibonacci_seq[-1] + Fibonacci_seq[-2]
    if next_i %2 ==0 and next_i < n:
        total += next_i
    Fibonacci_seq.append(next_i)
print(total)